apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: tkn
    - name: url
      value: https://github.com/IBM/cp4i-deployment-samples

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      #change this to the cluster's icp-console route
      value: default-route-openshift-image-registry.kbcl5-230239-ec111ed5d7db435e1c5eeeb4400d693f-0000.eu-gb.containers.appdomain.cloud

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-docker-image
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.git-source.path)/products/cicd/DOCKERFILE
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.inputs.git-source.path)/products/cicd
    - name: bar_file_name
      type: string
      description: Bar file name
    - name: imageNameTag
      type: string
      description: The name and the tag of the image to build
    - name: imageNamespace
      type: string
      description: Namespace to push built image to
  resources:
    inputs:
      - name: git-source
        type: git
    outputs:
      - name: docker-image
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.docker-image.url)/$(params.imageNamespace)/$(params.imageNameTag)
        - --context=$(params.pathToContext)
        - --build-arg=$(params.bar_file_name)
        - --verbosity=debug
        - --log-timestamp
        - --insecure-registry=$(resources.outputs.docker-image.url)
      securityContext:
        runAsUser: 0

---

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ace-pipeline
  namespace: ace
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.git-source.path)/products/cicd/DOCKERFILE
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.git-source.path)/products/cicd
    - name: bar_file_name
      type: string
      description: Bar file name
    - name: imageNameTag
      type: string
      description: The name and the tag of the image to build
    - name: imageNamespace
      type: string
      description: Namespace to push built image to
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: ace-run
      taskRef:
        name: build-push-docker-image
      params:
        - name: pathToDockerFile
          value: "$(params.pathToDockerFile)"
        - name: pathToContext
          value: "$(params.pathToContext)"
        - name: bar_file_name
          value: "$(params.bar_file_name)"
        - name: imageNameTag
          value: "$(params.imageNameTag)"
        - name: imageNamespace
          value: "$(params.imageNamespace)"
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image

# ---

# apiVersion: tekton.dev/v1beta1
# kind: PipelineRun
# metadata:
#   generateName: ace-pipeline-run-
# spec:
#   serviceAccountName: cicd-ace-sa
#   pipelineRef:
#     name: ace-pipeline
#   params:
#     - name: pathToDockerFile
#       value: $(resources.inputs.git-source.path)/products/cicd/DOCKERFILE
#     - name: pathToContext
#       value: $(resources.inputs.git-source.path)/products/cicd #configure: may change according to your source
#     - name: bar_file_name
#       value: bar_file_name=simpleGET.bar #this filename should be in the format "bar_file_name=<actual_bar_file_name_with_extension>"
#     - name: imageNameTag
#       value: test-4:latest
#     - name: imageNamespace
#       value: ace
#   resources:
#     - name: git-source
#       resourceRef:
#         name: git-source
#     - name: docker-image
#       resourceRef:
#         name: docker-image
