apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ace-pipeline
  namespace: ace
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: ace-run
      taskRef:
        name: build-push-docker-image
      # resources:
      #   inputs:
      #     - name: docker-source
      #       resource: git-source
      #   outputs:
      #     - name: builtImage
      #       resource: docker-image
